### ISSUE TITLE
GCC > 7 is not allowed

### ISSUE THREAD

**Issue by ignatovmg** [lupoglaz/TorchProteinLibrary#25]
Error i'm getting, trying to use GCC 8

In file included from /gpfs/software/cuda/10.0/include/cuda_runtime.h:83,
                 from <command-line>:
/gpfs/software/cuda/10.0/include/crt/host_config.h:129:2: error: #error -- unsupported GNU version! gcc versions later than 7 are not supported!
 #error -- unsupported GNU version! gcc versions later than 7 are not supported!
  ^~~~~
error: command '/gpfs/software/cuda/10.0/bin/nvcc' failed with exit status 1

**Comment by lupoglaz** [comment]
Sorry, I used CUDA version 10.0.130, it seems to work with g++ 7.4.0 Could you please write you nvcc and g++ versions? Also, check this compatibility table: https://gist.github.com/ax3l/9489132

**Comment by lupoglaz** [comment]
Update to nvcc version 10.1.105 should solve this problem.
